<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Поиск");
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.search",
	"main_catalog_search",
	Array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"IBLOCK_ID" => "5",
		"IBLOCK_TYPE" => "catalog",
		"LINE_ELEMENT_COUNT" => "3",
		"NO_WORD_LOGIC" => "N",
		"OFFERS_LIMIT" => "5",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main_pagination",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "3",
		"PRICE_CODE" => array(),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array("PRICE","STOCK_COUNT",""),
		"RESTART" => "N",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SHOW_PRICE_COUNT" => "1",
		"USE_LANGUAGE_GUESS" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_SEARCH_RESULT_ORDER" => "N",
		"USE_TITLE_RANK" => "N"
	)
);?>
<?//$APPLICATION->IncludeComponent(
//	"bitrix:search.page",
//	"main_search_page",
//	Array(
//		"AJAX_MODE" => "N",
//		"AJAX_OPTION_ADDITIONAL" => "",
//		"AJAX_OPTION_HISTORY" => "N",
//		"AJAX_OPTION_JUMP" => "N",
//		"AJAX_OPTION_STYLE" => "Y",
//		"CACHE_TIME" => "3600",
//		"CACHE_TYPE" => "A",
//		"CHECK_DATES" => "N",
//		"DEFAULT_SORT" => "rank",
//		"DISPLAY_BOTTOM_PAGER" => "Y",
//		"DISPLAY_TOP_PAGER" => "N",
//		"FILTER_NAME" => "",
//		"NO_WORD_LOGIC" => "N",
//		"PAGER_SHOW_ALWAYS" => "N",
//		"PAGER_TEMPLATE" => "main_pagination",
//		"PAGER_TITLE" => "Результаты поиска",
//		"PAGE_RESULT_COUNT" => "3",
//		"PATH_TO_USER_PROFILE" => "",
//		"RATING_TYPE" => "",
//		"RESTART" => "N",
//		"SHOW_RATING" => "",
//		"SHOW_WHEN" => "N",
//		"SHOW_WHERE" => "N",
//		"USE_LANGUAGE_GUESS" => "Y",
//		"USE_SUGGEST" => "N",
//		"USE_TITLE_RANK" => "N",
//		"arrFILTER" => array("iblock_catalog"),
//		"arrFILTER_iblock_catalog" => array("5"),
//		"arrWHERE" => ""
//	)
//);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>